### ISSUE TITLE
[ENTREGA TP1] playadito

### ISSUE THREAD

**Issue by abrilnimo** [pdep-lunes-tarde/2023-logico-tp-1-playadito#1]
Ahí ya esta el tp :)

@jschuhmann47 - Juani Schuhmann y @EmilianoSalvano - Emiliano Salvano

**Comment by EmilianoSalvano** [comment]
Buenas, perdón por la tardanza 😄

Lo único que voy a comentar es que está un poco flojo algunos nombres de predicados (ej: `odia` y `rico`)

Muy buen Tp!

**Comment by fueguino3** [comment]
Buenísimo! Vamos a intentar mejorar con el tema de la expresividad, nos confundimos pensando que iban esos por la consigna
